### ISSUE TITLE
Ticketing rethink

### ISSUE THREAD

**Issue by nbudin** [neinteractiveliterature/intercode#2585]
I've seen a few issues come in asking for very reasonable improvements to the ticket purchasing experience, as well as event-provided tickets, that I haven't come up with a great solution for.  Taken together, these seem to me to suggest that rethinking how tickets work is possibly necessary:

- [] Buying tickets for other people (#1351)
- [] Provide a mechanism for event-provided tickets to cost money (#2565)
- [] Optionally-limited-use coupon codes (#364)

Possibly also related but we could actually do these under the current design of tickets:

- [] Make ticket sales possible in single-event sites (#2283)
- [] Make event-provided tickets category-specific (#1383)

One thing that's occurred to me is that it's weird that we have two entirely separate systems for selling tickets and for selling other stuff (T-shirts, etc.).  If we could figure out some way of using the store system for also selling tickets, that would potentially make a lot of these features available for non-ticket products too.

**Comment by dkapell** [comment]
I don't actually mind that we have two different systems, because one is for "purchasable things that affect your website experience" and one is for "purchasable things that will be relevant later" . I've seen other orgs use a single storefront for both (NWM sells event tickets next to t-shirts) and it's always been really odd to me.

Maybe making it one thing behind the scenes and using properties to flag if a purchace "is a ticket"  and "provides event signups" (or even "provides X event signups" which would allow selling tickets good for 1 game each, buy as many as you want.  Intercon would just set that to unlimited)

**Comment by Quinn-D** [comment]
As I've been telling other organizations about Neil hosting as an option, the limitations to ticket pricing occasionally comes up. (One price available at a time).  One such organization runs on a "pay what you can, with suggested value" model.  It would be nice to have these other options.
